mercure:
    hubs:
        default:
            url: 'https://localhost/.well-known/mercure'
            public_url: 'https://localhost/.well-known/mercure'
            jwt:
                secret: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.isrXgf3K34RtyNfLu8rO7rR-uUVbd6hl_l6K31yEvZ0'
                publish: '*'
