version: '3'

services:
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    ports:
      - "3001:80"
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'your-256-bit-secretyour-256-bit-secret'
      MERCURE_SUBSCRIBER_JWT_KEY: 'your-256-bit-secretyour-256-bit-secret'

      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
        anonymous
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    volumes:
      - mercure_data:/data
      - mercure_config:/config
volumes:
  mercure_data:
  mercure_config:
