controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
fetch_updates:
    path: /dialog/{id}/updates
    controller: App\Controller\DialogController::fetchUpdates
